version: "3"
services:
  proxy:
    image: jonasal/nginx-certbot:latest
    network_mode: host
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./user_conf.d:/etc/nginx/user_conf.d"
      - "./letsencrypt:/etc/letsencrypt"
    env_file:
      - ./nginx-certbot.env
  admin:
    image: ghcr.io/sebastianusk/warehousia-admin
    restart: always
    ports:
      - "8080:80"
  api:
    image: ghcr.io/sebastianusk/warehousia-api
    restart: always
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/postgres"
    ports:
      - "3333:3333"
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - "./postgres:/var/lib/postgresql/data"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300
