version: "3"
services:
  proxy:
    image: jonasal/nginx-certbot:latest
    network_mode: host
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./user_conf.d:/etc/nginx/user_conf.d"
      - "./letsencrypt:/etc/letsencrypt"
    env_file:
      - ./nginx-certbot.env
  admin:
    image: ghcr.io/sebastianusk/warehousia-admin:latest
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - "api"
  api:
    image: ghcr.io/sebastianusk/warehousia-api:latest
    restart: always
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
      JWT_EXPIRES_IN: '1d'
    ports:
      - "3333:3333"
    depends_on:
      - "postgres"
  postgres:
    image: postgres:13.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./postgres:/var/lib/postgresql/data"
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
  watchtower:
    image: containrrr/watchtower:1.3.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 900
