openapi: 3.0.3
info:
  contact:
    name: example
    url: example
    email: example@example.com
  description: "API for warehousia application"
  version: 0.0.1
  title: Warehousia API
tags:
  - name: account
    description: Everything about the admins
  - name: warehouse
    description: The warehouse group, where you store your product
  - name: shop
    description: The shop group, it is where we sell the product
  - name: inbound
    description: Action where the product getting into the warehouse
  - name: transfer
    description: Action where the product moved from one warehouse to others
  - name: outbound
    description: Action where the product is planned to getting out from the warehouse
  - name: preparation
    description: Action where the product is prepared to leave the warehouse
  - name: product
    description: The detail about the product
  - name: transaction
    description: Action where product sold to the shop
paths:
  /login:
    post:
      tags:
        - account
      summary: Login API
      description: "API for login"
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: successully login
        "401":
          $ref: "#/components/responses/Unauthorized"
  /accounts:
    post:
      tags:
        - account
      summary: Create Admin
      operationId: create-admin
      description: "to create a new admin account"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                role:
                  type: string
                warehouse:
                  type: array
                  items:
                    type: string
      responses:
        "200":
          description: successfuly create admin
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Admin"
        "422":
          $ref: "#/components/responses/UnprocessableEntities"
        "401":
          $ref: "#/components/responses/Unauthorized"
    patch:
      tags:
        - account
      summary: Edit Admin
      description: Edit admin information
      operationId: edit-admin
      requestBody:
        content:
          applicaion/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                role:
                  type: string
                warehouse:
                  type: array
                  items:
                    type: string
      responses:
        "200":
          description: successfuly edit admin
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Admin"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "422":
          $ref: "#/components/responses/UnprocessableEntities"

externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://petstore.swagger.io/v2
components:
  responses:
    UnprocessableEntities:
      description: failed to process one of the field
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              properties:
                field:
                  type: string
                error:
                  type: string
    Unauthorized:
      description: access not allowed
      content:
        application/json:
          schema:
            type: string
  schemas:
    Admin:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        role:
          type: string
        warehouse:
          type: array
          items:
            type: string
        createdAt:
          type: string
        updatedAt:
          type: string
