openapi: 3.0.3
info:
  contact:
    name: example
    url: example
    email: example@example.com
  description: "API for warehousia application"
  version: 0.0.1
  title: Warehousia API
tags:
  - name: account
    description: Everything about the admins
  - name: warehouse
    description: The warehouse group, where you store your product
  - name: shop
    description: The shop group, it is where we sell the product
  - name: inbound
    description: Action where the product getting into the warehouse
  - name: transfer
    description: Action where the product moved from one warehouse to others
  - name: outbound
    description: Action where the product is planned to getting out from the warehouse
  - name: preparation
    description: Action where the product is prepared to leave the warehouse
  - name: product
    description: The detail about the product
  - name: transaction
    description: Action where product sold to the shop
paths:
  /login:
    post:
      tags:
        - account
      summary: Login API
      description: "API for login"
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: successully login
        "401":
          $ref: "#/components/responses/Unauthorized"
  /accounts:
    post:
      tags:
        - account
      summary: Create Admin
      description: "to create a new admin account"
      operationId: create-admin
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                role:
                  type: string
                warehouse:
                  type: array
                  items:
                    type: string
      responses:
        "200":
          description: successfuly create admin
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Admin"
        "422":
          $ref: "#/components/responses/UnprocessableEntities"
        "401":
          $ref: "#/components/responses/Unauthorized"
    get:
      operationId: get-admins
      tags:
        - account
      summary: Get Admin List
      description: Get All Admin list by super admin
      responses:
        "200":
          description: successfully get all admin
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Admin"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "422":
          $ref: "#/components/responses/UnprocessableEntities"
  /accounts/{username}:
    patch:
      operationId: edit-admin
      parameters:
        - name: username
          required: true
          in: path
          schema:
            type: string
      tags:
        - account
      summary: Edit Admin
      description: Edit admin information
      requestBody:
        $ref: "#/components/requestBodies/EditAdmin"
      responses:
        "200":
          description: successfuly edit admin
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Admin"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "422":
          $ref: "#/components/responses/UnprocessableEntities"
    delete:
      parameters:
        - name: username
          required: true
          in: path
          schema:
            type: string
      tags:
        - account
      operationId: delete-admin
      summary: Delete an Admin
      description: removing a admin
      responses:
        "200":
          description: successfully delete admin
        "401":
          $ref: "#/components/responses/Unauthorized"
        "422":
          $ref: "#/components/responses/UnprocessableEntities"

  /accounts/{username}/password:
    patch:
      operationId: change-others-password
      parameters:
        - name: username
          required: true
          in: path
          schema:
            type: string
      description: change other admin password by super admin
      summary: Change Other Admin Password
      tags:
        - account
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: successfully change other admin password
        "401":
          $ref: "#/components/responses/Unauthorized"
        "422":
          $ref: "#/components/responses/UnprocessableEntities"

  /accounts/me:
    patch:
      operationId: change-my-data
      description: change logged in admin's dta
      summary: Change my data
      tags:
        - account
      requestBody:
        $ref: "#/components/requestBodies/EditAdmin"
      responses:
        "200":
          description: successfuly edit admin
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Admin"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "422":
          $ref: "#/components/responses/UnprocessableEntities"

  /accounts/me/password:
    patch:
      operationId: change-my-password
      description: change logged in admin's password
      summary: Change my password
      tags:
        - account
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
      responses:
        "200":
          description: successfuly change my password
        "401":
          $ref: "#/components/responses/Unauthorized"
        "422":
          $ref: "#/components/responses/UnprocessableEntities"


servers:
  - url: https://petstore.swagger.io/v2
components:
  requestBodies:
    EditAdmin:
      content:
        application/json:
          schema:
            type: object
            properties:
              role:
                type: string
              warehouse:
                type: array
                items:
                  type: string

  responses:
    UnprocessableEntities:
      description: failed to process one of the field
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              properties:
                field:
                  type: string
                error:
                  type: string
    Unauthorized:
      description: access not allowed
      content:
        application/json:
          schema:
            type: string
  schemas:
    Admin:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        role:
          type: string
        warehouse:
          type: array
          items:
            type: string
        createdAt:
          type: string
        updatedAt:
          type: string
