apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: production
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: ghcr.io/sebastianusk/warehousia-admin@sha256:c499e92cdc9ea52f516868dd1ccb44adb6c025dbaa466c8be9a26a4d4abc715f
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
