apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: production
spec:
  ports:
    - port: 80
      targetPort: 3333
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/sebastianusk/warehousia-api:e2c852da5fb2695e22f04248484e8958fb80e09d
          imagePullPolicy: Always
          ports:
            - containerPort: 3333
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: DATABASE_URL
            - name: JWT_EXPIRES_IN
              value: '1d'
