apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: production
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: ghcr.io/sebastianusk/warehousia-admin:prod-84a48e0cb0d32f0a66da4386afccdf4b0b9c1343
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: '128Mi'
              cpu: '50m'
            limits:
              memory: '256Mi'
