apiVersion: v1
kind: Namespace
metadata:
  name: metabase
  labels:
    name: metabase
---
apiVersion: v1
kind: Service
metadata:
  name: metabase-svc
  namespace: metabase
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: metabase-dep
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase-dep
  namespace: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase-dep
  template:
    metadata:
      labels:
        app: metabase-dep
    spec:
      containers:
        - name: metabase
          image: metabase/metabase:v0.41.1
          ports:
            - containerPort: 3000
          env:
            - name: JAVA_OPTS
              value: -Xmx1g
            - name: MB_DB_TYPE
              value: postgres
            - name: MB_DB_DBNAME
              valueFrom:
                secretKeyRef:
                  name: metabase-secret
                  key: MB_DB_DBNAME
            - name: MB_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: metabase-secret
                  key: MB_DB_PORT
            - name: MB_DB_USER
              valueFrom:
                secretKeyRef:
                  name: metabase-secret
                  key: MB_DB_USER
            - name: MB_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: metabase-secret
                  key: MB_DB_PASS
            - name: MB_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: metabase-secret
                  key: MB_DB_HOST
