name: GitHub Actions Admin Warehousia
on: workflow_dispatch
env:
  REGISTRY: ghcr.io
jobs:
  Build-Admin-Prod:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.3]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: NX_GRAPHQL_HOST=https://gql.warehousia.com/graphql npm run build:admin
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build-admin
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/sebastianusk/warehousia-admin:latest, ghcr.io/sebastianusk/warehousia-admin:${{ github.sha }}
          file: ./apps/admin/docker/Dockerfile
          context: ./
