name: GitHub Actions Warehousia
on: [push]
env:
  REGISTRY: ghcr.io
jobs:
  Build-Apps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.3]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - name: build-admin
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: sebastianusk/warehousia-admin
          file: apps/admin/Dockerfile
      - name: build-api
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: sebastianusk/warehousia-api
          file: apps/api/Dockerfile
